[simulation]
timestep_s = 100e-6         # Simulation timestep
max_time_s = 100e-6            # Maximum time to run the simulation (in seconds)
output_interval = 100    # How frequently to output the deposition rates to chosen geometry
particle_weight = 1e11      # Carbon macroparticle weight
verbosity = 1
display = true

[plume]
origin = { x = 0.0, y = 0.2285, z = -2.125 }  # Location of the plume origin (in meters)
direction = { x = 0.0, y = 0.0, z = 1.0 }     # Orientation of the plume
background_pressure_Torr = 5e-6                     # Facility background pressure (in Torr)
ion_current_A = 15.0                                # Ion current in A
model_parameters = [0.8, 0.8, 14.0, 0.45, 6.31e18, 1.259e15, 55.0]  # Plume model parameters
beam_energy_eV = 300.0                              # Ion energy in the main beam
scattered_energy_eV = 300.0                         # Ion energy in the scattered beam
cex_energy_eV = 50.0                                # CEX ion energy

[chamber]
radius_m = 3
length_m = 10

[[material]]                                        # Define a surface material
name = "carbon"
color = { x = 0.3, y = 0.3, z = 0.3 }
temperature_K = 300                                 # Temperature (for diffuse reflections)
sticking_coeff = 0.3
diffuse_coeff = 0.7

[[geometry]]                                        # Define geometry 
name = "Thruster"                                   # Name
model = "thruster"                                   # Mesh file
material = "carbon"                                 # Which material to use
collect = false                                     # Whether to log particles that stick to this geometry
translate = { x = 0.0, y = 0.2285, z = -2.16 }      # Transformations (rotate, scale, translate) to apply to this mesh
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -90 }

# Further geometry definitions (beam dump, QCM, etc) follow

[[geometry]]
name = "QCM"
model = "square"
material = "carbon"
collect = true
scale = { x = 0.1241, y = 0.1241, z = 1.0 }
color = { x = 0.9, y = 0.1, z = 0.1 }
translate = { x = 1.0, y = 0.2285, z = -2.16 }

#[[geometry]]
#name = "chamber"
#model = "o_chamber.obj"
#material = "carbon"
#collect = false
#scale = { x = 1.0, y = 1.0, z = 1.0 }
#color = { x = 0.1, y = 0.2, z = 0.5 }
#translate = { x = 0.0, y = 0.0, z = 0.0 }

[[geometry]]
name = "beamdump_back_l"
model = "square"
material = "carbon"
smooth = true
scale = { x = 0.610, y = 0.610, z = 1.0 }
translate = { x = -0.334, y = 0.330, z = 2.074 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 0 }

[[geometry]]
name = "beamdump_back_r"
model = "square"
material = "carbon"
scale = { x = 0.610, y = 0.610, z = 1.0 }
translate = { x = 0.334, y = 0.330, z = 2.074 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 0 }

[[geometry]]
name = "beamdump_rt-1"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.219, z = 1.0 }
translate = { x = -0.138, y = 1.2575, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rt0"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.219, z = 1.0 }
translate = { x = -0.315, y = 1.2575, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rt1"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.219, z = 1.0 }
translate = { x = -0.492, y = 1.2575, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }


[[geometry]]
name = "beamdump_rt2"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -0.626, y = 0.9525, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rt3"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -0.845, y = 0.9525, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rt4"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -1.124, y = 0.9525, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rt5"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -1.383, y = 0.9525, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rt6"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -1.632, y = 0.9525, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rt7"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -1.881, y = 0.9525, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_lt-1"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.219, z = 1.0 }
translate = { x = 0.138, y = 1.2575, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lt0"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.219, z = 1.0 }
translate = { x = 0.315, y = 1.2575, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lt1"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.219, z = 1.0 }
translate = { x = 0.492, y = 1.2575, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }


[[geometry]]
name = "beamdump_lt2"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 0.626, y = 0.9525, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lt3"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 0.845, y = 0.9525, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lt4"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 1.124, y = 0.9525, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lt5"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 1.383, y = 0.9525, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lt6"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 1.632, y = 0.9525, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lt7"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 1.881, y = 0.9525, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_rb0"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -0.138, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rb1"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -0.377, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rb2"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -0.626, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rb3"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -0.845, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rb4"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -1.124, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rb5"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -1.383, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rb6"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -1.632, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_rb7"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = -1.881, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = 30 }

[[geometry]]
name = "beamdump_lb0"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 0.138, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lb1"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 0.387, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lb2"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 0.636, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lb3"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 0.885, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lb4"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 1.134, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lb5"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 1.383, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lb6"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 1.632, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }

[[geometry]]
name = "beamdump_lb7"
model = "square"
material = "carbon"
scale = { x = 0.305, y = 1.829, z = 1.0 }
translate = { x = 1.881, y = -0.9145, z = 2.0 }
rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -30 }
