[simulation]
timestep_s = 5e-6         # Simulation timestep
max_time_s = 5e-2            # Maximum time to run the simulation (in seconds)
output_interval = 1000
particle_weight = 1e8      # Carbon macroparticle weight
display = false
verbosity = 1

[plume]
origin = { z = -1.31 }  # Location of the plume origin (in meters)
direction = { z = 1.0 }     # Orientation of the plume
background_pressure_Torr = 6.2e-6                   # Facility background pressure (in Torr)
ion_current_A = 11.0                                # Ion current in A
model_parameters = [
    0.38, 0.3, 1.4, 0.18, 20.15, 16.0, 55.0
]  # Plume model parameters
beam_energy_eV = 600.0                              # Ion energy in the main beam
scattered_energy_eV = 500.0                         # Ion energy in the scattered beam
cex_energy_eV = 50.0                                # CEX ion energy
probe = true                                        # probe data should be output
probe_distance_m = 1.0
resample_interval = 1e-3

[chamber]
radius_m = 1
length_m = 2

[[material]]                                        # Define a surface material
name = "carbon"
color = 0.5
temperature_K = 300                                 # Temperature (for diffuse reflections)
sticking_coeff = 0.9
diffuse_coeff = 0.1
sputter = true

[[material]]                                        # Define a surface material
name = "nosputter"
color = 0.5
temperature_K = 100.0                              # Temperature (for diffuse reflections)
sticking_coeff = 1.0
diffuse_coeff = 0.05
sputter = false

#[[geometry]]                                        # Define geometry 
#name = "Thruster"                                   # Name
#model = "thruster"                             # Mesh model
#material = "nosputter"                                 # Which material to use
#collect = false                                     # Whether to log particles that stick to this geometry
#translate = { x = 0.0, y = 0, z = -1.37}      # Transformations (rotate, scale, translate) to apply to this mesh
#rotate = { axis = { x = 0.0, y = 1.0, z = 0.0 }, angle = -90 }

# C13 target
[[geometry]]
name = "target"
model = "square"
material = "carbon"
translate = { x = 0.0, y = -0.095, z = 0.0}
scale = 0.01 

## Target housing
#[[geometry]]
#name = "target-housing"
#model = "o_cylinder.obj"
#material = "nosputter"
#translate = {x = 0.0, y = -0.095, z = 0.005}
#scale = {x = 0.005, y = 0.01, z = 0.005}
#rotate = { axis = {x = 1.0, y = 0.0, z = 0.0}, angle = 90}

# Top array
[[geometry]]
name = "p1"
model = "square"
material = "carbon"
collect = true
color = 0.9 
translate = { x = -0.0735, y = -0.137025387, z = -0.09948802380109789}
scale = 0.00939 
rotate = {axis = {x = 1.0}, angle = 157.1}

[[geometry]]
name = "p2"
model = "square"
material = "carbon"
collect = true
color = 0.9 
translate = { x = -0.0535, y = -0.137025387, z = -0.09948802380109789}
scale = 0.01 
rotate = {axis = {x = 1.0}, angle = 157.1}

[[geometry]]
name = "p3"
model = "square"
material = "carbon"
collect = true
color = 0.9 
translate = { x = -0.037, y = -0.137025387, z = -0.09948802380109789}
scale = 0.01 
rotate = {axis = {x = 1.0}, angle = 157.1}

[[geometry]]
name = "p4"
model = "square"
material = "carbon"
collect = true
color = 0.9 
translate = { x = -0.0165, y = -0.137025387, z = -0.09948802380109789}
scale = 0.01 
rotate = {axis = {x = 1.0}, angle = 157.1}

[[geometry]]
name = "p5"
model = "square"
material = "carbon"
collect = true
color = 0.9 
translate = { x = 0.0165, y = -0.137025387, z = -0.09948802380109789}
scale = 0.01 
rotate = {axis = {x = 1.0}, angle = 157.1}

[[geometry]]
name = "p6"
model = "square"
material = "carbon"
collect = true
color = 0.9 
translate = { x = 0.037, y = -0.137025387, z = -0.09948802380109789}
scale = 0.01 
rotate = {axis = {x = 1.0}, angle = 157.1}

[[geometry]]
name = "p7"
model = "square"
material = "carbon"
collect = true
color = 0.9 
translate = { x = 0.0535, y = -0.137025387, z = -0.09948802380109789}
scale = 0.01 
rotate = {axis = {x = 1.0}, angle = 157.1}

[[geometry]]
name = "p8"
model = "square"
material = "carbon"
collect = true
color = 0.9 
translate = { x = 0.0735, y = -0.137025387, z = -0.09948802380109789}
scale = 0.01 
rotate = {axis = {x = 1.0}, angle = 157.1}

[[geometry]]
name = "top-array-body"
model = "cube"
material = "carbon"
color = 0.1 
translate = { y = -0.13900991876085733, z = -0.10418606936948308 }
scale = {x = 0.18, y = 0.015, z = 0.01}
rotate = {axis = {x = 1.0}, angle = 157.1}

# Bottom array
[[geometry]]
name = "p9"
model = "square"
material = "carbon"
collect = true
color = 0.9
translate = { x = -0.0735, y = -0.16561883, z = -0.06204}
scale = 0.01
rotate = {axis = {x = 1.0}, angle = 131.3}

[[geometry]]
name = "p10"
model = "square"
material = "carbon"
collect = true
color = 0.9
translate = { x = -0.0535, y = -0.16561883, z = -0.06204}
scale = 0.01
rotate = {axis = {x = 1.0}, angle = 131.3}

[[geometry]]
name = "p11"
model = "square"
material = "carbon"
collect = true
color = 0.9
translate = { x = -0.037, y = -0.16561883, z = -0.06204}
scale = 0.01
rotate = {axis = {x = 1.0}, angle = 131.3}

[[geometry]]
name = "p12"
model = "square"
material = "carbon"
collect = true
color = 0.9
translate = { x = -0.0165, y = -0.16561883, z = -0.06204}
scale = 0.01
rotate = {axis = {x = 1.0}, angle = 131.3}

[[geometry]]
name = "p13"
model = "square"
material = "carbon"
collect = true
color = 0.9
translate = { x = 0.0165, y = -0.16561883, z = -0.06204}
scale = 0.01
rotate = {axis = {x = 1.0}, angle = 131.3}

[[geometry]]
name = "p14"
model = "square"
material = "carbon"
collect = true
color = 0.9
translate = { x = 0.037, y = -0.16561883, z = -0.06204}
scale = 0.01
rotate = {axis = {x = 1.0}, angle = 131.3}

[[geometry]]
name = "p15"
model = "square"
material = "carbon"
collect = true
color = 0.9
translate = { x = 0.0535, y = -0.16561883, z = -0.06204}
scale = 0.01
rotate = {axis = {x = 1.0}, angle = 131.3}

[[geometry]]
name = "p16"
model = "square"
material = "carbon"
collect = true
color = 0.9
translate = { x = 0.0735, y = -0.16561883, z = -0.06204}
scale = 0.01
rotate = {axis = {x = 1.0}, angle = 131.3}

[[geometry]]
name = "bottom-array-body"
model = "cube"
material = "carbon"
color = 0.1 
translate = { y = -0.170, z = -0.0653 }
scale = {x = 0.18, y = 0.015, z = 0.01}
rotate = {axis = {x = 1.0}, angle = 131.3}

[[geometry]]
name = "shield"
model = "square"
material = "nosputter"
collect = false
sputter = false
translate = [0.0, -0.605, -0.15]
